### ISSUE TITLE
Add NewtonScript reference to all programming terms

### ISSUE THREAD

**Issue by splorp** [splorp/newton-glossary#27]
For clarity, any NewtonScript-specific terms should include NewtonScript as a related term. Likewise, term descriptions should probably start with some sort of reference to NewtonScript itself.

For example:

>### Region
>
>In [NewtonScript](http://newtonglossary.com/terms/newtonscript), an arbitrary area or set of areas on the coordinate plane, specifically when referring to the contents of a [view](http://newtonglossary.com/terms/view). The outline of a region should be one or more closed loops.

**Comment by splorp** [comment]
Closed per commit [5b077df](https://github.com/splorp/newton-glossary/commit/5b077df8d3d480b48b4f7d4fcb92cea7fdfad8d8)

**Comment by splorp** [comment]
Probably should go back and add an opening reference to NewtonScript to the term definition (where applicable) as shown in the example.

**Comment by splorp** [comment]
Second time’s the charm.

Closed per commit c482a6f

**Comment by splorp** [comment]
There are still a handful of programmatic terms missing an opening reference to NewtonScript.

Example:

https://newtonglossary.com/terms/data-form
https://newtonglossary.com/terms/event
https://newtonglossary.com/terms/magic-pointer

**Comment by splorp** [comment]
Closed per commit [22f99d2](https://github.com/splorp/newton-glossary/commit/22f99d269b4b922726094912535e646d0bc9719d)

**Comment by luxuryluke** [comment]
👍
