### ISSUE TITLE
Separate page for Newton code names

### ISSUE THREAD

**Issue by splorp** [splorp/newton-glossary#40]
Another potential resource for the site could be a separate page listing all of the code names for various Newton devices, linking back to entries in the glossary.

Just a thought.

**Comment by SylvainPilet** [comment]
Hi grant,
It would be good indeed. Do you want to talk about the Newtons code names and/or Newton compatible materials?

**Comment by splorp** [comment]
Sure, let’s discuss that here.

**Comment by da4089** [comment]
So, perhaps a term for "codenames", with a list of links to the individual pages?

Figaro
Cadillac
Bic
Senior
Mont Blanc
Newton Plus

Batman  (early OMP)
Junior (MP100)
Lindy (MP110/120/130?)
Q (MP2k)

There's a bunch of these in /source/appledesign

Is this the kind of thing you're after Grant?

**Comment by splorp** [comment]
I don’t think that we need to create a term for _code name_ or _codename_ or _codenames_.

I was thinking of simply adding a separate page which lists the various codenames that are already terms in the glossary (like you’ve listed above). We‘d also add a link in the main navigation pointing directly at that page.

**Comment by splorp** [comment]
Here’s a list of all the code name terms currently in the glossary:

- Andante
- Batman
- Bazooka
- Bic
- Cadillac
- Cirrus
- Copperfield
- Crib
- Dante
- Denali
- Gelato
- Hobbit
- Jellyfish
- Junior
- Lindy
- Mondello
- Mont Blanc
- N2
- Neuropen
- Newton Plus
- Pocket Newton
- Project K
- Q
- Quark
- Rosetta
- Runt
- Santa Fe
- Schoolbook
- Senior
- Shay
- Wedge

**Comment by splorp** [comment]
After thinking about this for a while, it might make more sense to add a question to the [Newton FAQ](https://newtonfaq.com/) such as:

_What are the various Newton code names?_

This general page of information seems like a better fit in the FAQ than the Glossary, but could certainly be cross-linked between the two.

**Comment by SylvainPilet** [comment]
Grant,Indeed, while reading the FAQ again today, I had this thought. A dedicated question would be nice. Even if this information can be found in the table with the characteristics of the Newton, having a direct entry in the FAQ would be better.SylvainLe 28 janv. 2022 à 21:56, Grant Hutchinson ***@***.***> a écrit :After thinking about this for a while, it might make more sense to add a question to the Newton FAQ such as:What are the various Newton code names?This general page of information seems like a better fit in the FAQ than the Glossary, but could certainly be cross-linked between the two.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.

**Comment by SylvainPilet** [comment]
Grant,

Indeed, while reading the FAQ again today, I had this thought. A dedicated question would be nice. Even if this information can be found in the table with the characteristics of the Newton, having a direct entry in the FAQ would be better.

Sylvain

**Comment by splorp** [comment]
> Even if this information can be found in the table with the characteristics of the Newton, having a direct entry in the FAQ would be better.

I’m trying to determine where the best place to include the new entry. The list of code names includes terms for hardware, software, and portions of the OS itself.

My initial thinking is to create a new question after [Where can I find information about Newton prototypes?](http://newtonfaq.com/newton-faq-hardware.html#IIA1l) on the Hardware page (IIA1l).

Prototypes and code names are definitely linked together during the product development process.

And as you mentioned, since there are already code names listed in the [Newton Specifications](http://newtonfaq.com/newton-faq-hardware.html#IIA1e) table, perhaps the Hardware page is the most logical choice.

**Comment by SylvainPilet** [comment]
For the code names of everything hardware put them in the hardware section makes sense. 
As for the other list of code names in the section, software, NewtonOS, Prototypes...
Either a single list in the Hardware section that gathers all the code names (Hardware, Software, NewtonOS...)
But a list in each section makes sense with each section and would be more in accordance with the FAQ as it is organized today. One could put a link to every other list of code names in each of these lists, so the reader will know that other lists exist.

I would put this entry (for the Hardware list) either just before or just after "Where can I find information about Newton prototypes?" (IIA1l). 

Hope to have helped you.

**Comment by splorp** [comment]
My solution to this is to create an entirely new page in the FAQ called “Background” … this section will contain general information and questions about the Newton platform not found anywhere else in the FAQ.

Background information will include a timeline of significant events, links to archived press releases, the list of code names, as well as publications, articles, and papers focused on our little green friend.

Stay tuned.

**Comment by splorp** [comment]
Moved issue to the [Newton FAQ](https://github.com/splorp/newton-faq/)
