### ISSUE TITLE
Migrate site to Kirby 3

### ISSUE THREAD

**Issue by splorp** [splorp/newton-glossary#43]
When doing so, apparently plugins may need to be renamed in order to work correctly with the new version.

cf. https://github.com/shoesforindustry/kirby-plugins-alphabetise/issues/4#issue-384930543

**Comment by shoesforindustry** [comment]
this should now be fixed.

**Comment by splorp** [comment]
Duly noted. Thanks for the update!

**Comment by splorp** [comment]
Completed in release [3.0.0](https://github.com/splorp/newton-glossary/releases/tag/3.0.0)
